[package]
name = "flexml_render"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
flexml_dom = { path = "../flexml_dom" }
vello = "0.5.0"
anyhow = "1.0.98"
pollster = "0.4.0"
png = "0.17"
futures-intrusive = "0.5"
wgpu = "24.0.5"