[package]
name = "flexml_dom"
version = "0.0.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
url = "2.5.4"
logos = "0.15.0"
ariadne = "0.5.1"
bitflags = "2.9.1"
paste = "1.0.15"
taffy = "0.8.3"
parley = "0.5.0"